name: ci

on:
  push:
    branches: [ main ]
    paths: [ "gateway/**", "gantry/**", "proto/**", "loggrpc/**", "pkg/**", ".github/workflows/ci.yml" ]
  pull_request:
    paths: [ "gateway/**", "gantry/**", "proto/**", "loggrpc/**", "pkg/**", ".github/workflows/ci.yml" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  proto-verify:
    name: Proto lint & generated code check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: proto

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: proto/go.mod
          cache: true

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: buf lint
        run: buf lint

      - name: buf generate
        run: buf generate

      - name: Verify generated code committed
        run: |
          git add -N gen
          git diff --exit-code -- gen || \
            (echo "::error ::Generated protobuf is out of date. Run 'buf generate' in ./proto and commit changes." && exit 1)

      - name: Verify go.work.sum is synced
        working-directory: ${{ github.workspace }}
        run: |
          if [ -f go.work ]; then
            go work sync
            git diff --exit-code -- go.work.sum || \
              (echo "::error ::go.work.sum changed. Commit the updated file or run 'go work sync' locally." && exit 1)
          fi

  go-build-test:
    name: Build & test modules
    runs-on: ubuntu-latest
    needs: proto-verify
    strategy:
      fail-fast: false
      matrix:
        module: [ 'gantry', 'gateway', 'pkg' ]
    defaults:
      run:
        working-directory: ${{ matrix.module }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.module }}/go.mod
          cache: true

      - name: go mod tidy (${{ matrix.module }})
        #working-directory: ${{ matrix.module }}
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum || \
            (echo "::error ::${{ matrix.module }} go.mod/go.sum not tidy. Run 'go mod tidy' and commit." && exit 1)

      - name: Build (${{ matrix.module }})
        #working-directory: ${{ matrix.module }}
        run: go build ./...

      - name: Test (${{ matrix.module }})
        #working-directory: ${{ matrix.module }}
        run: go test -race -count=1 ./...
